name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14' # Define the elixir version [required]
        otp-version: '25.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests with lcov --exit
      run: mix lcov --exit
    - name: Upload code coverage
      uses: actions/upload-artifact@v3
      with:
        name: lcov-file
        path: cover/lcov.info

  coverage_report:
    name: Generate coverage report
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download code coverage reports
      uses: actions/download-artifact@v3
      with:
        name: lcov-file
        path: cover
    - name: Report code coverage
      uses: kefasjw/lcov-pull-request-report@v1
      with:
        # Lcov file location
        lcov-file: cover/lcov.info
        # Github token required for getting list of changed files and posting comments
        github-token: ${{ secrets.GITHUB_TOKEN }}